### ISSUE TITLE
Cant create testnet account with m.lisk.io 

### ISSUE THREAD

**Issue by kankando** [LiskHQ/lisk-nano#1043]
### Expected behaviour
1. Go to m.lisk.io and select testnet
2. Click on new account button
3. generate passphrase and key in passphrase
4. should be able to logon testnet

### Actual behavior
1. Go to m.lisk.io and select testnet
2. Click on new account button
** Seem the network being reset to mainnet when you click new account**
3. generate passphrase and key in passphrase
4.  and failed to logon testnet

### Steps to reproduce
1. Go to m.lisk.io and select testnet
2. Click on new account button
** Seem the network being reset to mainnet when you click new account**
3. generate passphrase and key in passphrase
4.  and failed to logon testnet

**Comment by slaweet** [comment]
Hi @kankando,
thank you for reporting the problem. More or less the same problem was already reported in https://github.com/LiskHQ/lisk-nano/issues/1031 so we have it on our radar to fix it in [Version 2.0.0](https://github.com/LiskHQ/lisk-nano/projects/7). I'll close this one as duplicate.

In the meantime, note that you can use the passphrase generated for mainnet also to log in with testnet, because the account is not saved on blockchain until you actually send some LSK to it.

**Comment by webmaster128** [comment]
> In the meantime, note that you can use the passphrase generated for mainnet also to log in with testnet, because the account is not saved on blockchain until you actually send some LSK to it.

Haha, interesting hack. Thanks for sharing!
