### ISSUE TITLE
Signed message output missing publickey for cold accounts

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-nano#152]
### Expected behaviour

```
-----BEGIN LISK SIGNED MESSAGE-----
Test Message
-----BEGIN SIGNATURE-----
37f950fce7051400629cc1a82879b954bbeb6844235b72158f0a49bbc90b14b2
3eb1937b1489859d063e0db66dc902777ec666e7e46801cac007e07da833673cafd4e784901377d93523ce60e1f7478f52f3cffa089c8ce10b8bb0226b2c9b0b54657374204d657373616765
-----END LISK SIGNED MESSAGE-----
```

### Actual behaviour

```
-----BEGIN LISK SIGNED MESSAGE-----
Test Message
-----BEGIN SIGNATURE-----

3eb1937b1489859d063e0db66dc902777ec666e7e46801cac007e07da833673cafd4e784901377d93523ce60e1f7478f52f3cffa089c8ce10b8bb0226b2c9b0b54657374204d657373616765
-----END LISK SIGNED MESSAGE-----
```

### Steps to reproduce

1. Login using the new account wizard
2. Click `Sign Message` from menu
3. Enter a `Message` to sign

**Comment by karmacoma** [comment]
Related code:

https://github.com/LiskHQ/lisk-nano/blob/development/src/app/components/sign-verify/sign-message.js#L17

https://github.com/LiskHQ/lisk-js/blob/development/lib/transactions/crypto/sign.js#L45

**Comment by slaweet** [comment]
This got fixed since @alihaghighatkhah created Account service, which always sets publicKey:
https://github.com/LiskHQ/lisk-nano/blob/development/src/app/services/account.js#L13
And updated sign-message component to use it:
https://github.com/LiskHQ/lisk-nano/blob/development/src/app/components/sign-verify/sign-message.js#L15
