### ISSUE TITLE
Sign/verify message should contain some explanation

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-nano#181]
### Actual behaviour
Sign/verify message dialogs are very empty and to a new user of cryptocurrencies, their purpose might not be obvious.
![sign-message](https://cloud.githubusercontent.com/assets/1254342/25793903/de410f0e-33ce-11e7-8ae3-55b2454dd7ec.png)
### Expected behaviour
Some explanation text could be added there to explain the features.
Either it can be done as in the voting dialog:
![vote](https://cloud.githubusercontent.com/assets/1254342/25793956/22f5d1ac-33cf-11e7-9246-340591c27e83.png)
Or some tooltip:
![tooltip](https://cloud.githubusercontent.com/assets/1254342/25794718/78121e9a-33d2-11e7-87e8-4a5ec3e5d344.png)

**Comment by slaweet** [comment]
@karmacoma , @Isabello , can you please put down here some suggestions on what the explanation for Sign message dialogue and Verify message dialogue should say? It would be also nice to put there some "Learn more" link, if there is a relevant web page.

**Comment by Tosch110** [comment]
With signing a message you can create a digital signature of your message with the account you are using in lisk nano. Your privateKey will be used in order to create the signature and other people can then use the signature and your publicKey in order to verify that this message was signed by the owner of the Lisk account. But also be aware, since computers can be tampered and various forms of viruses can be used to take over computers, a digital signature is not a 100% proof that the message comes from the right person. Nonetheless, when used appropriately, digital signatures are extremely useful.
Note: Digital Signatures and signed messages are not encrypted!

**Comment by Isabello** [comment]
Signing a message with this tool indicates ownership of a privateKey (secret) and provides a level of proof that you are the owner of the key. Its important to bear in mind that this is not a 100% proof as computer systems can be compromised, but is still an effective tool for proving ownership of a particular publicKey/address pair.

Note: Digital Signatures and signed messages are not encrypted!

**Comment by Tosch110** [comment]
When you have the signature, you only need the publicKey of the signer in order to verify that the message came from the right private/publicKey pair. Be aware, everybody knowing the signature and the publicKey can verify the message. If ever there is a dispute, everybody can take the publicKey and signature to a judge and prove that the message is coming from the specific private/publicKey pair.
