### ISSUE TITLE
Forging tab should be always visible

### ISSUE THREAD

**Issue by karmacoma** [LiskHQ/lisk-nano#218]
### Expected behaviour

User should be able to click on a visible "Forging" tab and then: "Register as a delegate".

### Actual behaviour

No forging tab is displayed.

Secondly, by navigating to the route `/#/main/forging` for a non-delegate, the user is presented with a disabled button: "Become Delegate". Therefore a dead end.

![image](https://cloud.githubusercontent.com/assets/8068/26055695/41503c7a-3972-11e7-8517-248a457fdff1.png)

### Steps to reproduce

Log in as a non-delegate.

**Comment by slaweet** [comment]
Forging tab always visible was the case when I first implemented it. But it was requested (by @karmacoma or @MaxKK) to make it NOT visible if not delegate. 

I'm for keeping it NOT always visible because of UX. Delegates should be by definition just a small percentage of users and for the rest, it just hinders the UI.

The only think that IMO needs to be solved is that `/#/main/forging` should redirect to `/#/main/transactions` if not delegate account.

**Comment by karmacoma** [comment]
@slaweet During testing I found the "Forging" tab popping up out of nowhere largely invisible to new users after registering as a delegate.

Regardless, the routing issue needs to be resolved, the dead end message I attached should be replaced with a redirect at the very least.

**Comment by alihaghighatkhah** [comment]
I would suggest,  
**The template:**
We can add a message informing about the reason for the redirection instead.
**The tab:**
We can show it only after the delegate registration transaction is confirmed.

**Comment by MaxKK** [comment]
I agree to @slaweet, it doesn't need to be shown if the account is not a delegate. 

**Later on**, we need to think about a way how to introduce changes to the UI. Maybe a slick animation, instead of just a random popup. For now, I would say no need to change **in regards** to the animation. There is more important things to do.
