### ISSUE TITLE
Can't open a wallet with a secret

### ISSUE THREAD

**Issue by Crypto2** [LiskHQ/lisk-nano#249]
I have an old school address I want to open where I only have the secret/password like is passed to the Lisk API, but the wallet expects a passphrase only and won't let me open the wallet with it.

### Expected behaviour
Enter secret/password, click login, wallet opens.
### Actual behaviour
Text field highlights orange and won't allow login.

**Comment by mms6261** [comment]
I created a wallet and transferred my coins from Poloniex. The coins arrived, but when I tried to log in it will not recognize my passphrase. I checked and all words appear on the word list.

**Comment by Crypto2** [comment]
@mms6261 That would be a different issue, this ticket is about opening a wallet using a secret instead of a passphrase.

**Comment by Crypto2** [comment]
Any update on this?

**Comment by slaweet** [comment]
We discussed this issue in LiskHQ and the conclusion is that we won't support this in Lisk Nano because it goes against our mission to make and keep Lisk secure and simple. 
- Not requiring 12-word passphrase allows end users to use secrets with not-hight-enough entropy.
- Adding and supporting more login options adds complexity to the code and UI that will not be used by the vast majority of users.

**Comment by mms6261** [comment]
Why am I getting this email? 

    On Monday, August 14, 2017 4:39 AM, Vít Stanislav <notifications@github.com> wrote:
 

 We discussed this issue in LiskHQ and the conclusion is that we won't support this in Lisk Nano because it goes against our mission to make and keep Lisk secure and simple.   
   - Not requiring 12-word passphrase allows end users to use secrets with not-hight-enough entropy.
   - Adding and supporting more login options adds complexity to the code and UI that will not be used by the vast majority of users.

**Comment by slaweet** [comment]
@mms6261 you commented on this issue and because of that Github automatically subscribes you to the issue. You change that in Github setting.
