### ISSUE TITLE
Remove access to 'Register as delegate' form for delegates

### ISSUE THREAD

**Issue by ginacontrino** [LiskHQ/lisk-nano#946]
### Expected behaviour
A delegate should not be able to see the "Register as delegate" form

### Actual behaviour
If a delegate visits `main/voting/register-delegate` the form pops up

### Steps to reproduce
- Log in as a delegate
- Go to http://localhost:8080/#/main/voting/register-delegate

<img width="1667" alt="screen shot 2017-11-02 at 14 20 26" src="https://user-images.githubusercontent.com/9592216/32328198-866e2590-bfd9-11e7-9281-518d8bc4d143.png">

**Comment by joerodrig** [comment]
I would like to help with this. Are there any resources showing a way to simulate the delegate account state and coins?

**Comment by joerodrig** [comment]
@ginacontrino It appears that this form disables the "register" button if the account is already a delegate. See [registerDelegate.js - line 70](https://github.com/LiskHQ/lisk-nano/blob/development/src/components/registerDelegate/registerDelegate.js#L70). Could this be the expected behavior and there just aren't specs written for that case?

**Comment by ginacontrino** [comment]
@joerodrig Hey, yes that's correct. The button is correctly disabled, because in this case, the user is already a delegate. In general, they shouldn't be able to access this form at all though, so it's better to instead display a message that informs the user about why they can't visit the route 'main/voting/register-delegate'. A test that checks that the error message is displayed, would be nice of course :)
